### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by jaggederest** [taylorlapeyre/basicwardrobe.info#13]
I'd like to send a pull request, but I can't unless there's a license file :)

Thanks!

**Comment by taylorlapeyre** [comment]
Sorry, I'll get right on that!

**Comment by taylorlapeyre** [comment]
Added: https://github.com/taylorlapeyre/basic-wardrobe/commit/478e31b15454a1e6a9e03652fb45212ec625cd23
