### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by baptistemarchand** [taylorlapeyre/basicwardrobe.info#16]
Hi,
The following links are broken:
- [x] Left Field NYC Crossgrain Ringspun Terry (tops/sweaters)
- [x] Uniqlo Cashmere V-Neck (tops/sweaters)
- [x] Gitman Brothers 2-Ply Dress Shirt (formal attire/dress shirts)

frugal:
- [ ] Unbranded Indigo UB201 (bottoms/jeans)
- [ ] Stafford Prep Chino Shorts (bottoms/shorts)
- [ ] Mossimo Supply Co. Men's Short Sleeve Tee (tops/tees)
- [ ] Alternate Apparel Boss V Neck (tops/tees)
- [ ] jcp Fine Gauge Cardigan (tops/sweaters)
- [ ] Uniqlo Lambswool Sweater (tops/sweaters)
- [ ] Aldo Mr.B Blake Wingtip Boots (shoes/boots)
- [ ] Supra Cutter Low "Two" (shoes/sneakers)
- [ ] all the casual leather shoes links
- [ ] Brooks Brothers Extra Slim Fit Striped Dress Shirt (formal attire/dress shirts)
- [ ] Timex Slip Thru Weekender (extras/watches)

I don't have time to fix them all but I thought it would be a good idea to have a list.

**Comment by taylorlapeyre** [comment]
Thanks for this! I'm going to do an update of the site very soon. I'll check off the links that I fix as I fix them.
