### ISSUE TITLE
Non-raw denim suggestions

### ISSUE THREAD

**Issue by christianbundy** [taylorlapeyre/basicwardrobe.info#17]
For some (myself included) raw denim seems to be too big of a hassle – I can't imagine wearing jeans that will stain things that I sit on. Are there any suggestions you'd make for non-raw denim? Thanks!

**Comment by taylorlapeyre** [comment]
Hey there! If you're looking for washed denim, then the difference in quality will drastically even out to "mediocre" regardless of the brand. Because of this, I'd suggest sticking with Levi's.

**Comment by moxieman** [comment]
That's pretty much entirely incorrect. If you don't want "raw denim" just wash them. You'll have nice quality denim and they won't rub off on everything. Suggesting you shouldn't bother buying nice jeans unless you plan on wearing them raw is preposterous.

**Comment by taylorlapeyre** [comment]
@moxieman Sure, there is washed denim out there that is made with a lot of care and effort. I'm not implying that raw denim is the _only_ choice for wearing jeans, of course not.

However, I can only talk from my own personal experience with my clothes, in which I found that denim brands that specialize in making raw denim tend to have much higher quality standards. The washed denim that I've actually worn was also made very well, but had about the same lifespan has a normal pair of Levis.

Like I said, this is my experience. It is likely different from yours.
