### ISSUE TITLE
Site down.

### ISSUE THREAD

**Issue by bruncun** [taylorlapeyre/basicwardrobe.info#23]
Seems to be stuck in infinite redirect loop. Resources still accessible from data directory.

**Comment by taylorlapeyre** [comment]
@bruncun I'll get on it. Weird - probably a DNS issue.

**Comment by taylorlapeyre** [comment]
Quick fix was to delete the CNAME file. Current behavior is that it redirects to taylorlapeyre.com/basicwardrobe.info, which isn't ideal, but it works for now.

Thanks for the heads up!
