### ISSUE TITLE
Add a "frugal" option for each item

### ISSUE THREAD

**Issue by taylorlapeyre** [taylorlapeyre/basicwardrobe.info#7]
> Many people looking to get a basic wardrobe won't want to spend top dollar right away.

We could provide a "budget" suggested item for each thing.

From [nbes](http://www.reddit.com/r/malefashionadvice/comments/18vygw/the_recent_basic_wardrobe_posts_inspired_me_to/c8ijj1w):

> For Chinos:
> - Bonobos Slim Fit Chinos (my absolute favorite)
> - J. Crew Broken In Chinos
> 
> For Shorts:
> - Uniqlo Chino Shorts
> 
> For Oxford Button Downs:
> - Uniqlo + JCP
> 
> For Patterned Button Ups:
> - Bonobos
> - GAP
> - Uniqlo
> 
> For Sweaters:
> - J. Crew or J. Crew Factory
> - GAP
> - Old Navy
> 
> For Sneakers:
> - Vans
> 
> For Leather Shoes:
> - LL Bean Camp Mocs
> 
> For Blazer and Suit:
> - Factory Thompson from J. Crew Factory (best value/fit and it comes in charcoal, > grey, and navy. Even after tailoring, it's still a great inexpensive alternative.)
> 
> For Dress Shoes:
> - Alden's are a good alternative as well!
> - Maybe Cole Haan?

From [Interrobang_](http://www.reddit.com/r/malefashionadvice/comments/18vygw/the_recent_basic_wardrobe_posts_inspired_me_to/c8ilz20):

> Here are some dress shoes:
> 
> http://www.jcpenney.com/dotcom/stafford-ashton-mens-wingtip-dress-shoes/prod.> jump?ppId=1b9aceb
> 
> http://www.jcpenney.com/dotcom/men/stafford-alex-mens-oxfords/prod.> jump?ppId=pp5001521741&cmvc=JCP> |SearchResults|RICHREL&grView=&eventRootCatId=&currentTabCatId=&regId=
> 
> http://www.jcpenney.com/dotcom//shoes/mens-shoes/dress-shoes/claiborne-gaylord-suede-> oxford-dress-shoes/prod.jump?ppId=pp5002301337&catId=cat100420003&deptId=dept20000014&> dimCombo=null&dimComboVal=null
> 
> Hattip to dappered.com, which is where I've heard about most of these.

**Comment by jinpark** [comment]
This might be better as a sister site to this one. I like that the focus on the current site is on higher quality pieces.

**Comment by taylorlapeyre** [comment]
Published to /frugal
