### ISSUE TITLE
Accordion around sections?

### ISSUE THREAD

**Issue by jaggederest** [taylorlapeyre/basicwardrobe.info#8]
I like the layout of the site, but it'd be interesting to see what a version with accordions around each section looks like (i.e. pants, shirts, outerwear, dress)

**Comment by taylorlapeyre** [comment]
Very interesting idea. Shouldn't be too difficult to implement either.

I are two obvious solutions:
1. Use bootstrap-accordion.js (we'd have to redo the HTML layout)
2. Simple jQuery animations for li height attributes
